# Generated by Django 2.2 on 2020-11-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yewonMemberApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='newsletter_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='newsletter_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
