# Generated by Django 2.2 on 2020-11-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yewonMemberApp', '0003_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='title',
            field=models.TextField(default='Title'),
            preserve_default=False,
        ),
    ]
